name: Production deployment

on:
  push:
    branches:
      - master
      
env:
  AZURE_RESOURCE_GROUP: github-labs-app
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"West Europe"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: molnar-atesz-tictactoe
  #################################################
